config/routes.rb
Rails.application.routes.draw do

  root 'top_pages#home'
  get 'about' => 'top_pages#about'
  get 'help' => 'top_pages#help'
  get 'search'   => 'shops#index'
  get 'prefectures' => 'prefectures#index'
  get 'prefectures/:id' => 'prefectures#show', :as => :prefecture
  get 'rank'      => 'shops#ranking'
  get 'shops/:id'  => 'shops#show', :as => :shop
  get 'chat'      => 'rooms#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  #コミットした後にブロードキャストする
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :shops
  validates(:name, presence: true)

  HOKKAIDO_IDS = 1
  TOHOKU_IDS = [2..7]
  KANTOU_IDS = [8..14]
  HOKURIKU_IDS = [15..18]
  CHUBU_IDS = [19..24]
  KANSAI_IDS = [25..30]
  CHUGOKU_IDS = [31..35]
  SHIKOKU_IDS = [36..39]
  KYUSHU_IDS = [40..46]
  OKINAWA_IDS = 47

  scope :hokkaido, -> { where(id: HOKKAIDO_IDS) }
  scope :tohoku,   -> { where(id: TOHOKU_IDS) }
  scope :kantou,   -> { where(id: KANTOU_IDS) }
  scope :hokuriku, -> { where(id: HOKURIKU_IDS) }
  scope :chubu,    -> { where(id: CHUBU_IDS) }
  scope :kansai,   -> { where(id: KANSAI_IDS) }
  scope :chugoku,  -> { where(id: CHUGOKU_IDS) }
  scope :shikoku,  -> { where(id: SHIKOKU_IDS) }
  scope :kyushu,   -> { where(id: KYUSHU_IDS) }
  scope :okinawa,  -> { where(id: OKINAWA_IDS) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
  validates(:star, presence: true)
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :prefecture
  has_many :reviews
  validates(:name, presence: true)
  validates(:address, presence: true)
  validates(:tel, presence: true)
  validates(:open_time, presence: true)
  validates(:close_time, presence: true)
  validates(:evaluation, presence: true)
  geocoded_by :address
  after_validation :geocode

  scope :keyword_search, -> (q) {
    where("name LIKE :q ESCAPE '\\' OR about LIKE :q ESCAPE '\\'", { q: "%#{sanitize_sql_like(q.to_s)}%"})
  }
  has_attached_file :image, styles: { medium: "240x240" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def create_area
      @japan_areas =
      {
        '北海道'  => Prefecture.hokkaido,
        '東北'   => Prefecture.tohoku,
        '関東'   => Prefecture.kantou,
        '北陸'   => Prefecture.hokuriku,
        '中部'   => Prefecture.chubu,
        '関西'   => Prefecture.kansai,
        '中国'   => Prefecture.chugoku,
        '四国'   => Prefecture.shikoku,
        '九州'   => Prefecture.kyushu,
        '沖縄'   => Prefecture.okinawa
      }
    end
    
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  before_action :create_area, only: [:index]
  def index
  end

  def show
    @prefecture_name = Prefecture.find(params[:id])
    @shops = @prefecture_name.shops.paginate(page: params[:page])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
    @messages = Message.all
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def home
    @shops = [{name: "一番星", address: "宮城県仙台市青葉区八幡５丁目１−１２"}, {name: "一二三", address: "宮城県仙台市青葉区国分町２丁目１３−２"}, {name: "一閃閣", address: "宮城県仙台市青葉区国分町2−10−10"}]
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @search_keyword = index_params[:q]
    @shops = Shop.keyword_search(@search_keyword).paginate(page: params[:page])
  end

  def show
    @shop = Shop.find(params[:id])
  end

  private
    def index_params
      params.permit(:q)
    end

end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  before_action :create_area, only: [:home]

  def home
  end

  def help
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとのタイトルを返す
  def full_title(page_title = '')
    base_title = 'ラーメンデータベース'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "about", about_path %></li>
      <li><%= link_to "help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-nav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ラーメンサイト", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="top-nav">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "検索", search_path %></li>
        <li><%= link_to "地域別", prefectures_path %></li>
        <li><%= link_to "ランキング", '#' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?v=3.23"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='/javascripts/gmaps_google.js'></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= message.content %></p>
</div>

app/views/prefectures/index.html.erb
<% provide(:title, "地域別検索") %>
<h1>都道府県から選択してね</h1>
<%= render 'shared/area_list' %>

app/views/prefectures/show.html.erb
<% provide(:title, "#{@prefecture_name.name}一覧") %>
<div class="row">
  <div class="col-md-4">
    <h1><%= @prefecture_name.name %>のラーメン店</h1>
  </div>
  <div class="col-md-8">
    <%= will_paginate(@shops) %>
    <ul class="shops list-group">
      <% @shops.each do |shop| %>
        <li class="list-group-item">
          <section>
            <h4><%= link_to shop.name, shop %></h4>
            <address><%= "#{shop.prefecture.name}#{shop.address}" %></address>
          </section>
        </li>
      <% end %>
    </ul>
    <%= will_paginate(@shops) %>
  </div>
</div>

app/views/rooms/show.html.erb
<h1>チャット</h1>
<div id="messages">
  <%= render @messages %>
</div>

<form>
  <small>なんかどうぞ:</small>
  <input type="text" data-behavior="room_speaker">
</form>

app/views/searches/home.html.erb
<h3>キーワード検索</h3>
<input></input>

<h2>検索結果</h2>

<% @shops.each do |shop| %>
  <li>
    <h4><%= shop[:name] %></h4>
    <p><%= shop[:address] %></p>
  </li>
<% end %>

app/views/shared/_area_list.html.erb
<table class="table table-striped table-condenced">
  <% @japan_areas.each do |area, prefectures| %>
    <tr>
      <td><%= area %></td>
      <% prefectures.each do |p| %>
        <td> <%= link_to p.name, prefecture_path(p) %> <td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/shared/_search_form.html.erb
<div class='form-group'>
  <%= form_tag(search_path, method: 'get') do %>
    <div class="row">
      <div class="col-xs-8">
        <%= text_field_tag(:q, '', class: 'form-control') %>
      </div>
      <div class="col-xs-4">
        <%= submit_tag('検索', name: nil, class: 'btn btn-default') %>
      </div>
    </div>
  <% end %>
</div>

app/views/shops/index.html.erb
<% if params[:q].blank? %>
  <% provide(:title, '検索ページ') %>
  <h1>検索で探す</h1>
<% else %>
  <% provide(:title, params[:q] + 'の検索結果') %>
  <h1>検索結果</h1>
<% end %>

<div class="row">
  <div class="col-md-4">
    <h2>検索で探す</h2>
    <%= render 'shared/search_form' %>
  </div>
  <div class="col-md-8">
    <p>
      <% if params[:q].present? %>
        検索キーワード：<%= @search_keyword %>
      <% end %>
    </p>
    <%= will_paginate %>

    <ul class="shops list-group">
      <% @shops.each do |shop| %>
        <li class="list-group-item">
          <section>
            <h4><%= link_to shop.name, shop %></h4>
            <address><%= "#{shop.prefecture.name}#{shop.address}" %></address>
          </section>
        </li>
      <% end %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/shops/show.html.erb
<% provide(:title, @shop.name.to_s) %>

<div class="row">
  <div class="col-md-8">
    <table class="table table-striped">
      <caption>
        <h1><%= @shop.name %></h1>
      </caption>
      <tbody>
        <tr>
          <th>住所</th>
          <td><%= "#{@shop.prefecture.name}#{@shop.address}" %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @shop.tel %></td>
        </tr>
        <tr>
          <th>営業時間</th>
          <td><%= "#{@shop.open_time.strftime("%k:%M")} 〜 #{@shop.close_time.strftime("%k:%M")}" %></td>
        </tr>
        <tr>
          <th>定休日</th>
          <td><%= @shop.holiday %></td>
        </tr>
        <tr>
          <th>概要</th>
          <td><%= @shop.about %></td>
        </tr>
        <tr>
          <th>評価</th>
          <td><%= @shop.evaluation %></td>
        </tr>
      </tbody>
    </table>
    <div>
      <%= image_tag @shop.image.url(:medium) %>
    </div>
  </div>
  <div class="col-md-4">
    <br><br>
    <div style='width: 300px;'>
      <div id="map" style='width: 300px; height: 300px;'></div>
    </div>
  </div>
</div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      zoom: 15,
      center:    new google.maps.LatLng(<%= @shop.latitude %>, <%= @shop.longitude %>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    },
    internal: {id: 'map'}}, function(){
      markers = handler.addMarkers([
      { lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %> }
    ]);
  });
</script>

app/views/top_pages/about.html.erb
<% provide(:title, "ラーメンデータベースもどきについて") %>
<h1>aboutの場所</h1>
<p>hoge</p>

app/views/top_pages/help.html.erb
<% provide(:title, "ヘルプ") %>
<h1>helpの場所</h1>
<p>hoge</p>

app/views/top_pages/home.html.erb
<div class='jumbotron'>
  <h1>ラーメンさがすよ〜〜〜</h1>
</div>

<div class='row'>
  <div class='col-md-4'>
    <h2>検索で探す</h2>
    <%= render 'shared/search_form' %>
  </div>
  <div class='col-md-8'>
    <h2>都道府県から探す</h2>
    <%= render 'shared/area_list' %>
  </div>
</div>